// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoIntegradorSofttek.DataAccess;

#nullable disable

namespace TrabajoIntegradorSofttek.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TrabajoIntegradorSofttek.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("proyecto_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("proyecto_activo");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("proyecto_direccion");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("proyecto_estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("proyecto_nombre");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Direccion = "Santa Fe 674, Rio Negro",
                            Estado = 1,
                            Nombre = "Vaca Muerta"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Direccion = "Cajaraville 1093, Neuquen",
                            Estado = 2,
                            Nombre = "Nueva Nieve"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Direccion = "Los Ceibos 5732, Chubut",
                            Estado = 3,
                            Nombre = "Salinas Rojas"
                        });
                });

            modelBuilder.Entity("TrabajoIntegradorSofttek.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("servicio_activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("servicio_descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("servicio_estado");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("servicio_valorHora");

                    b.HasKey("Id");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Descripcion = "Perforacion",
                            Estado = true,
                            ValorHora = 500m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Descripcion = "Extraccion",
                            Estado = true,
                            ValorHora = 400m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Descripcion = "Transporte",
                            Estado = true,
                            ValorHora = 300m
                        });
                });

            modelBuilder.Entity("TrabajoIntegradorSofttek.Entities.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trabajo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("trabajo_activo");

                    b.Property<int>("CantHoras")
                        .HasColumnType("int")
                        .HasColumnName("trabajo_cantHoras");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("trabajo_costo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("trabajo_fecha");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int")
                        .HasColumnName("trabajo_idProyecto");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("trabajo_idServicio");

                    b.Property<decimal>("ValorHora")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("trabajo_valorHora");

                    b.HasKey("Id");

                    b.ToTable("Trabajos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CantHoras = 1000,
                            Costo = 150000m,
                            Fecha = new DateTime(2023, 9, 13, 0, 16, 4, 467, DateTimeKind.Local).AddTicks(5924),
                            IdProyecto = 1,
                            IdServicio = 1,
                            ValorHora = 150m
                        });
                });

            modelBuilder.Entity("TrabajoIntegradorSofttek.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("usuario_activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("usuario_clave");

                    b.Property<int>("Dni")
                        .HasColumnType("int")
                        .HasColumnName("usuario_dni");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("usuario_nombre");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("usuario_tipo");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Clave = "1234",
                            Dni = 41826520,
                            Nombre = "Franco",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Clave = "1234",
                            Dni = 11824320,
                            Nombre = "Eliana",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Clave = "1234",
                            Dni = 42446530,
                            Nombre = "Juan",
                            Tipo = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
